### ISSUE TITLE
<div>Add Registration Incentives<div> to Registration under Send payment to:

### ISSUE THREAD

**Issue by ctava** [gnyi/US-Gym-GNYI#15]
Interested in coming to the 2017 GNYI?  We’ll make it worth the trip!! 

We love seeing those gyms and coaches who have attended year after year (thank YOU!).  We also love welcoming new gyms and teams to the GNYI. 

Coaches can earn $100 - $250 in incentive payments! 
Register 10 - 19 more gymnasts than last year per group – girls, boys or Excel -- and your head coach for that group will receive $100!  (Not sure how many gymnasts you brought last year?  Just ask! We have that info for you by group.)

Register 20 or more gymnasts than last year per group, and that group’s head coach will receive $250!

New to the GNYI or your gymnasts couldn’t make it last year? This incentive applies to gyms or groups that did not attend the GNYI in 2016.  

Important Details:

Boys, girls and Xcel are each treated as separate groups.  Bringing a combination of gymnasts across groups (e.g., 5 more boys and 5 more girls) does not qualify for the incentive.  
To qualify, gymnasts must be registered and paid in full by November 10, 2017.
Number of gymnasts determined as of November 11, 2017.  (If after November 11, 2017, number of gymnasts must be approved by the GNYI Meet Directors.)
If a gym brings 10 more girls, 10 more boys and 10 more Xcel gymnasts, then the head coach of each group would receive $100, for a total GNYI payout of $300.  
The payment(s) will be made to the Head Coach listed on the registration form and given to that head coach at the GNYI Coaches Registration Table when s/he registers

**Comment by glappen** [comment]
@ctava - I was not sure about the formatting on this, but I put the content in.  Font size and style can be refined if necessary.
