### ISSUE TITLE
format registration page to be like the attached image

### ISSUE THREAD

**Issue by ctava** [gnyi/US-Gym-GNYI#18]
![registration](https://user-images.githubusercontent.com/283711/28649489-3597d028-7243-11e7-82fd-dd0a3d0df9d0.jpg)

**Comment by glappen** [comment]
@ctava - I applied the above formatting, but also kept the text below the horizontal rule about the cash incentives because the content above references it.  Let me know if further changes are required, or if isue can be closed.  Thanks!
