### ISSUE TITLE
Update hotel information - add link to doubletree.hilton.com (see specific link in description)

### ISSUE THREAD

**Issue by ctava** [gnyi/US-Gym-GNYI#3]
http://doubletree.hilton.com/en/dt/groups/personalized/N/NYCNADT-GNY-20171130/index.jhtml?WT.mc_id=POG

**Comment by glappen** [comment]
@ctava - I took my best guess on this one and added an h2 Hotel heading and called the link "DoubleTree by Hilton".  Let me know if it requires any adjustment.  Thanks!

**Comment by ctava** [comment]
this works. likely more changes down the road. Thanks!
